export const motorcycleVehicles = [
  {
    id: 'motorcycle-1',
    type: 'Moto',
    name: 'Yamaha R1',
    title: 'YAMAHA R1',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '120.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '299 KM/H', percentage: 88 },
      { title: 'Aceleração', value: '3.2 S', percentage: 92 },
      { title: 'Tração', value: 'RWD', percentage: 60 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-2',
    type: 'Moto',
    name: 'Kawasaki Ninja H2',
    title: 'NINJA H2',
    category: 'Motos',
    diamondPrice: '150',
    cardPrice: '340',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '331 KM/H', percentage: 100 },
      { title: 'Aceleração', value: '2.9 S', percentage: 100 },
      { title: 'Tração', value: 'RWD', percentage: 68 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-3',
    type: 'Moto',
    name: 'BMW S1000RR',
    title: 'BMW S1000RR',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '160.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '303 KM/H', percentage: 92 },
      { title: 'Aceleração', value: '3.1 S', percentage: 95 },
      { title: 'Tração', value: 'RWD', percentage: 64 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-4',
    type: 'Moto',
    name: 'Ducati Panigale',
    title: 'PANIGALE V4',
    category: 'Motos',
    diamondPrice: '90',
    cardPrice: '260',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '310 KM/H', percentage: 96 },
      { title: 'Aceleração', value: '3.0 S', percentage: 98 },
      { title: 'Tração', value: 'RWD', percentage: 66 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-5',
    type: 'Moto',
    name: 'Honda CBR1000RR',
    title: 'CBR1000RR',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '140.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '286 KM/H', percentage: 82 },
      { title: 'Aceleração', value: '3.4 S', percentage: 88 },
      { title: 'Tração', value: 'RWD', percentage: 58 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-6',
    type: 'Moto',
    name: 'Suzuki Hayabusa',
    title: 'HAYABUSA',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '180.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '312 KM/H', percentage: 97 },
      { title: 'Aceleração', value: '3.3 S', percentage: 94 },
      { title: 'Tração', value: 'RWD', percentage: 60 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-7',
    type: 'Moto',
    name: 'MT-09',
    title: 'YAMAHA MT-09',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '78.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '240 KM/H', percentage: 65 },
      { title: 'Aceleração', value: '3.8 S', percentage: 76 },
      { title: 'Tração', value: 'RWD', percentage: 54 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-8',
    type: 'Moto',
    name: 'Harley Fat Boy',
    title: 'FAT BOY',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '95.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '185 KM/H', percentage: 42 },
      { title: 'Aceleração', value: '5.5 S', percentage: 48 },
      { title: 'Tração', value: 'RWD', percentage: 50 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },

  {
    id: 'motorcycle-9',
    type: 'Moto',
    name: 'Triumph Street Triple',
    title: 'STREET TRIPLE',
    category: 'Motos',
    diamondPrice: '0',
    cardPrice: '89.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '252 KM/H', percentage: 68 },
      { title: 'Aceleração', value: '3.7 S', percentage: 78 },
      { title: 'Tração', value: 'RWD', percentage: 56 },
      { title: 'Porta Malas', value: '0 L', percentage: 5 },
    ],
  },
];
