export const sedanVehicles = [
  {
    id: 'sedan-1',
    type: 'Sedan',
    name: 'Mercedes C180',
    title: 'MERCEDES C180',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '280.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '223 KM/H', percentage: 48 },
      { title: 'Aceleração', value: '7.8 S', percentage: 42 },
      { title: 'Tração', value: 'RWD', percentage: 50 },
      { title: 'Porta Malas', value: '455 L', percentage: 60 },
    ],
  },

  {
    id: 'sedan-2',
    type: 'Sedan',
    name: 'Audi A4',
    title: 'AUDI A4',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '310.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '240 KM/H', percentage: 55 },
      { title: 'Aceleração', value: '6.9 S', percentage: 58 },
      { title: 'Tração', value: 'AWD', percentage: 60 },
      { title: 'Porta Malas', value: '460 L', percentage: 62 },
    ],
  },

  {
    id: 'sedan-3',
    type: 'Sedan',
    name: 'BMW 540i',
    title: 'BMW 540I',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '420.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '250 KM/H', percentage: 68 },
      { title: 'Aceleração', value: '5.1 S', percentage: 74 },
      { title: 'Tração', value: 'AWD', percentage: 70 },
      { title: 'Porta Malas', value: '530 L', percentage: 72 },
    ],
  },

  {
    id: 'sedan-4',
    type: 'Sedan',
    name: 'Honda Civic Touring',
    title: 'HONDA CIVIC',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '190.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '210 KM/H', percentage: 44 },
      { title: 'Aceleração', value: '8.4 S', percentage: 38 },
      { title: 'Tração', value: 'FWD', percentage: 42 },
      { title: 'Porta Malas', value: '525 L', percentage: 70 },
    ],
  },

  {
    id: 'sedan-5',
    type: 'Sedan',
    name: 'Toyota Corolla GR',
    title: 'COROLLA GR',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '210.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '225 KM/H', percentage: 50 },
      { title: 'Aceleração', value: '7.2 S', percentage: 56 },
      { title: 'Tração', value: 'FWD', percentage: 44 },
      { title: 'Porta Malas', value: '470 L', percentage: 64 },
    ],
  },

  {
    id: 'sedan-6',
    type: 'Sedan',
    name: 'Lexus IS350',
    title: 'LEXUS IS350',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '330.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '245 KM/H', percentage: 62 },
      { title: 'Aceleração', value: '6.0 S', percentage: 66 },
      { title: 'Tração', value: 'RWD', percentage: 65 },
      { title: 'Porta Malas', value: '480 L', percentage: 65 },
    ],
  },

  {
    id: 'sedan-7',
    type: 'Sedan',
    name: 'Audi RS7',
    title: 'AUDI RS7',
    category: 'Sedans',
    diamondPrice: '500',
    cardPrice: '950',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '305 KM/H', percentage: 95 },
      { title: 'Aceleração', value: '3.5 S', percentage: 98 },
      { title: 'Tração', value: 'AWD', percentage: 90 },
      { title: 'Porta Malas', value: '535 L', percentage: 80 },
    ],
  },

  {
    id: 'sedan-8',
    type: 'Sedan',
    name: 'Porsche Panamera',
    title: 'PANAMERA',
    category: 'Sedans',
    diamondPrice: '350',
    cardPrice: '780',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '295 KM/H', percentage: 90 },
      { title: 'Aceleração', value: '3.9 S', percentage: 92 },
      { title: 'Tração', value: 'AWD', percentage: 88 },
      { title: 'Porta Malas', value: '495 L', percentage: 72 },
    ],
  },

  {
    id: 'sedan-9',
    type: 'Sedan',
    name: 'Genesis G70',
    title: 'GENESIS G70',
    category: 'Sedans',
    diamondPrice: '0',
    cardPrice: '290.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '238 KM/H', percentage: 58 },
      { title: 'Aceleração', value: '6.4 S', percentage: 60 },
      { title: 'Tração', value: 'RWD', percentage: 55 },
      { title: 'Porta Malas', value: '450 L', percentage: 58 },
    ],
  },
];
