export const suvVehicles = [
  {
    id: 'suv-1',
    type: 'SUV',
    name: 'Range Rover Sport',
    title: 'RANGE ROVER SPORT',
    category: 'SUVS',
    diamondPrice: '0',
    cardPrice: '720.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '234 KM/H', percentage: 55 },
      { title: 'Aceleração', value: '6.0 S', percentage: 62 },
      { title: 'Tração', value: 'AWD', percentage: 75 },
      { title: 'Porta Malas', value: '647 L', percentage: 85 },
    ],
  },

  {
    id: 'suv-2',
    type: 'SUV',
    name: 'BMW X6',
    title: 'BMW X6',
    category: 'SUVS',
    diamondPrice: '0',
    cardPrice: '680.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '250 KM/H', percentage: 70 },
      { title: 'Aceleração', value: '5.5 S', percentage: 74 },
      { title: 'Tração', value: 'AWD', percentage: 82 },
      { title: 'Porta Malas', value: '580 L', percentage: 75 },
    ],
  },

  {
    id: 'suv-3',
    type: 'SUV',
    name: 'Audi Q8',
    title: 'AUDI Q8',
    category: 'SUVS',
    diamondPrice: '0',
    cardPrice: '750.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '245 KM/H', percentage: 68 },
      { title: 'Aceleração', value: '5.9 S', percentage: 70 },
      { title: 'Tração', value: 'AWD', percentage: 80 },
      { title: 'Porta Malas', value: '605 L', percentage: 78 },
    ],
  },

  {
    id: 'suv-4',
    type: 'SUV',
    name: 'Jeep Grand Cherokee',
    title: 'GRAND CHEROKEE',
    category: 'SUVS',
    diamondPrice: '0',
    cardPrice: '420.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '210 KM/H', percentage: 48 },
      { title: 'Aceleração', value: '7.1 S', percentage: 52 },
      { title: 'Tração', value: '4X4', percentage: 84 },
      { title: 'Porta Malas', value: '782 L', percentage: 92 },
    ],
  },

  {
    id: 'suv-5',
    type: 'SUV',
    name: 'Porsche Cayenne',
    title: 'PORSCHE CAYENNE',
    category: 'SUVS',
    diamondPrice: '250',
    cardPrice: '620',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '273 KM/H', percentage: 85 },
      { title: 'Aceleração', value: '4.8 S', percentage: 88 },
      { title: 'Tração', value: 'AWD', percentage: 90 },
      { title: 'Porta Malas', value: '698 L', percentage: 86 },
    ],
  },

  {
    id: 'suv-6',
    type: 'SUV',
    name: 'Lamborghini Urus',
    title: 'LAMBORGHINI URUS',
    category: 'SUVS',
    diamondPrice: '600',
    cardPrice: '1200',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '305 KM/H', percentage: 98 },
      { title: 'Aceleração', value: '3.6 S', percentage: 99 },
      { title: 'Tração', value: 'AWD', percentage: 94 },
      { title: 'Porta Malas', value: '616 L', percentage: 80 },
    ],
  },

  {
    id: 'suv-7',
    type: 'SUV',
    name: 'Mercedes G63',
    title: 'MERCEDES G63',
    category: 'SUVS',
    diamondPrice: '400',
    cardPrice: '980',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '240 KM/H', percentage: 72 },
      { title: 'Aceleração', value: '4.5 S', percentage: 92 },
      { title: 'Tração', value: '4X4', percentage: 96 },
      { title: 'Porta Malas', value: '667 L', percentage: 88 },
    ],
  },

  {
    id: 'suv-8',
    type: 'SUV',
    name: 'Volvo XC90',
    title: 'VOLVO XC90',
    category: 'SUVS',
    diamondPrice: '0',
    cardPrice: '390.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '215 KM/H', percentage: 50 },
      { title: 'Aceleração', value: '6.8 S', percentage: 60 },
      { title: 'Tração', value: 'AWD', percentage: 82 },
      { title: 'Porta Malas', value: '640 L', percentage: 84 },
    ],
  },

  {
    id: 'suv-9',
    type: 'SUV',
    name: 'Toyota SW4',
    title: 'TOYOTA SW4',
    category: 'SUVS',
    diamondPrice: '0',
    cardPrice: '370.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '190 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '9.5 S', percentage: 34 },
      { title: 'Tração', value: '4X4', percentage: 88 },
      { title: 'Porta Malas', value: '500 L', percentage: 72 },
    ],
  },
];
