export const truckVehicles = [
  {
    id: 'truck-1',
    type: 'Caminhão',
    name: 'Scania R450',
    title: 'SCANIA R450',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '850.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '130 KM/H', percentage: 30 },
      { title: 'Aceleração', value: '18 S', percentage: 18 },
      { title: 'Tração', value: '6X2', percentage: 80 },
      { title: 'Carga', value: '45 T', percentage: 95 },
    ],
  },

  {
    id: 'truck-2',
    type: 'Caminhão',
    name: 'Volvo FH540',
    title: 'VOLVO FH540',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '910.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '135 KM/H', percentage: 34 },
      { title: 'Aceleração', value: '17 S', percentage: 22 },
      { title: 'Tração', value: '6X4', percentage: 88 },
      { title: 'Carga', value: '50 T', percentage: 98 },
    ],
  },

  {
    id: 'truck-3',
    type: 'Caminhão',
    name: 'Mercedes Actros',
    title: 'MERCEDES ACTROS',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '790.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '128 KM/H', percentage: 28 },
      { title: 'Aceleração', value: '19 S', percentage: 18 },
      { title: 'Tração', value: '6X2', percentage: 82 },
      { title: 'Carga', value: '42 T', percentage: 92 },
    ],
  },

  {
    id: 'truck-4',
    type: 'Caminhão',
    name: 'DAF XF',
    title: 'DAF XF',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '720.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '125 KM/H', percentage: 25 },
      { title: 'Aceleração', value: '20 S', percentage: 15 },
      { title: 'Tração', value: '6X2', percentage: 78 },
      { title: 'Carga', value: '40 T', percentage: 88 },
    ],
  },

  {
    id: 'truck-5',
    type: 'Caminhão',
    name: 'Iveco Hi-Way',
    title: 'IVECO HI-WAY',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '680.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '122 KM/H', percentage: 22 },
      { title: 'Aceleração', value: '21 S', percentage: 12 },
      { title: 'Tração', value: '6X2', percentage: 76 },
      { title: 'Carga', value: '38 T', percentage: 82 },
    ],
  },

  {
    id: 'truck-6',
    type: 'Caminhão',
    name: 'MAN TGX',
    title: 'MAN TGX',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '760.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '132 KM/H', percentage: 32 },
      { title: 'Aceleração', value: '18 S', percentage: 20 },
      { title: 'Tração', value: '6X4', percentage: 86 },
      { title: 'Carga', value: '47 T', percentage: 95 },
    ],
  },

  {
    id: 'truck-7',
    type: 'Caminhão',
    name: 'Ford Cargo',
    title: 'FORD CARGO',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '540.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '118 KM/H', percentage: 18 },
      { title: 'Aceleração', value: '24 S', percentage: 10 },
      { title: 'Tração', value: '4X2', percentage: 68 },
      { title: 'Carga', value: '28 T', percentage: 70 },
    ],
  },

  {
    id: 'truck-8',
    type: 'Caminhão',
    name: 'Volkswagen Meteor',
    title: 'VW METEOR',
    category: 'Caminhões',
    diamondPrice: '0',
    cardPrice: '650.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '126 KM/H', percentage: 26 },
      { title: 'Aceleração', value: '20 S', percentage: 14 },
      { title: 'Tração', value: '6X2', percentage: 80 },
      { title: 'Carga', value: '41 T', percentage: 90 },
    ],
  },

  {
    id: 'truck-9',
    type: 'Caminhão',
    name: 'Kenworth W900',
    title: 'KENWORTH W900',
    category: 'Caminhões',
    diamondPrice: '100',
    cardPrice: '240',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '145 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '15 S', percentage: 30 },
      { title: 'Tração', value: '8X4', percentage: 95 },
      { title: 'Carga', value: '60 T', percentage: 100 },
    ],
  },
];
