export const categories = ['Competitivos', 'Esportivos', 'Sedans', 'SUVS', 'Motos', 'Caminhões'];

export const vehicles = [
  {
    id: 1,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 2,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 3,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 4,
    type: 'Exclusivo\nVIP',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 5,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 6,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 7,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 8,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
  {
    id: 9,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '202 KM/H', percentage: 40 },
      { title: 'Tração', value: '202 KM/H', percentage: 40 },
      { title: 'Porta Malas', value: '202 KM/H', percentage: 40 },
    ],
  },
];
