export const userBalance = {
  money: 'R$ 5.000.000',
  diamonds: '1.000',
};

export const vehicles = [
  {
    id: 1,
    type: 'Esportivo',
    name: 'Bmw 320i',
    title: 'BMW 320I',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 300.000',
    diamondPrice: '0',
    cardPrice: '300.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '202 KM/H', percentage: 40 },
      { title: 'Aceleração', value: '7.1 S', percentage: 45 },
      { title: 'Tração', value: 'RWD', percentage: 50 },
      { title: 'Porta Malas', value: '480 L', percentage: 65 },
    ],
  },
  {
    id: 2,
    type: 'Esportivo',
    name: 'Bmw 320i Sport',
    title: 'BMW 320I SPORT',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 350.000',
    diamondPrice: '0',
    cardPrice: '350.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '240 KM/H', percentage: 55 },
      { title: 'Aceleração', value: '6.8 S', percentage: 58 },
      { title: 'Tração', value: 'RWD', percentage: 50 },
      { title: 'Porta Malas', value: '470 L', percentage: 63 },
    ],
  },
  {
    id: 3,
    type: 'Esportivo',
    name: 'Bmw 320i M',
    title: 'BMW 320I M',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 420.000',
    diamondPrice: '0',
    cardPrice: '420.000',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: false,
    stats: [
      { title: 'Velocidade Máxima', value: '250 KM/H', percentage: 62 },
      { title: 'Aceleração', value: '6.2 S', percentage: 65 },
      { title: 'Tração', value: 'RWD', percentage: 58 },
      { title: 'Porta Malas', value: '460 L', percentage: 60 },
    ],
  },
  {
    id: 4,
    type: 'Exclusivo\nVIP',
    name: 'Skyline R34',
    title: 'SKYLINE R34',
    category: 'Veículos esportivos',
    moneyPrice: 'R$ 5.000.000',
    diamondPrice: '1.000',
    cardPrice: '300',
    image: '/imgs/cars/bmw-320i.png',
    exclusive: true,
    stats: [
      { title: 'Velocidade Máxima', value: '280 KM/H', percentage: 80 },
      { title: 'Aceleração', value: '4.9 S', percentage: 75 },
      { title: 'Tração', value: 'AWD', percentage: 70 },
      { title: 'Porta Malas', value: '180 L', percentage: 35 },
    ],
  },
];
